fixes:
  - "*/site-packages/::src/"

# Let's make the coverage threshold reports "informational" instead of blocking for now.
# Details here: https://docs.codecov.com/docs/quick-start#tips-and-tricks
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
