name: Create draft release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    env:
      plugin_name: "otio_template_plugin"

    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: otio-template-plugin{{ github.ref }}
          body: |
            Changes in this release
            * something
            * something

            Please upgrade your adapter with `pip install --upgrade ${{ env.plugin_name }}`
          draft: true
          prerelease: false
